Initial comit
hhru-school/segment-admin-panel-front pull request #2
Opened 2023-04-03 22:22 UTC by vagrmv

Собран проект через CRA с шаблоном redux-typescript.
Добавлены и настроены eslint и prettier.
Из проекта подчистил "лишние" файлы.
Добавлены пакеты для работы с material ui.

Есть вопрос по конфигу eslint. В хх конфиге в разделе правил подтягиваются правила из других пакетов, в том числе из одного хх пакета. Немного не разобрался в них. На данном этапе закомментировал правила к ним относящиеся. Прошу подсказать по их настройке

2023-04-04 06:22 UTC, Beken-S commented on .eslintignore
> +package.json
Надо добавить новую строку в конце.

2023-04-04 06:26 UTC, Beken-S commented on public/index.html
> +<html lang="en">
Я думаю мы на русском будем делать.

2023-04-04 07:49 UTC, sabkaryan requested changes

2023-04-04 07:49 UTC, sabkaryan commented on src/features/counter/Counter.tsx
> +}
Кажется эта страница с примером нам не нужна. Она нигде не импортится

2023-04-04 07:49 UTC, sabkaryan commented on src/features/counter/Counter.module.css
> +}
У нас будет material-ui эти стили нам не нужны

2023-04-04 07:49 UTC, sabkaryan commented on package.json
> +  },
Давай все версии зафиксируем

2023-04-04 07:49 UTC, sabkaryan commented on .eslintrc.js
> +        // '@hh.ru/import-rules/hh-import-order': 'error',
это правило можешь удалить, в остальных никакого криминала не вижу

2023-04-04 11:09 UTC, sabkaryan commented on package.json
> +    "magic_poof": "eslint . --ext .js,.jsx,.ts,.tsx"
желательно из названия команды понимать что она делать

2023-04-04 14:02 UTC, Beken-S commented on .eslintrc.js
> +        // '@hh.ru/import-rules/hh-import-order': 'error',
У меня получилось добавить правила таким образом:
- устанавливаем пакеты:
  ```sh
     yarn add -D @hh.ru/eslint-config eslint-plugin-etc eslint-import-resolver-typescript
  ```
- добавляем настроки в package.json:
```json
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest",
      "@hh.ru/eslint-config"
    ],
    "settings": {
      "import/parsers": {
        "@typescript-eslint/parser": [
          ".ts",
          ".tsx"
        ]
      },
      "import/resolver": {
        "typescript": {}
      }
    },
    "overrides": [
      {
        "files": "*.{ts,tsx}",
        "extends": "@hh.ru/eslint-config/typescript"
      }
    ]
  },
```
А prettier я думаю можно не добавлять а сделать просто автофоматирование как в доке CRA написанно.

2023-04-07 10:13 UTC, sabkaryan approved these changes

2023-04-07 15:54 UTC, merged